# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-03 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('numero', models.IntegerField()),
                ('images', models.NullBooleanField()),
                ('liens_vues', models.NullBooleanField()),
                ('_contenu', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='partie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='le_voyage_dans_l_espace.Partie'),
        ),
    ]
