name: Publish Docker Image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Publish Docker image
      uses: elgohr/Publish-Docker-Github-Action@2.9
      with:
        name: jujulego/tpe-web
        username: jujulego
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
