name: Build & Publish Docker Image

on:
  push:
    tags:
    - '[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set Env
      run: |
        echo ::set-env name=IMAGE_NAME::docker.pkg.github.com/jujulego/tpe/tpe-web
        echo ::set-env name=IMAGE_TAG::$(echo ${GITHUB_REF:10})
    - name: Login to Github registry
      run: docker login docker.pkg.github.com -u jujulego -p ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image
      run: docker build -t tpe-web .
    - name: Publish Docker image
      run: |
        docker tag tpe-web $IMAGE_NAME:latest
        docker tag tpe-web $IMAGE_NAME:$IMAGE_TAG
        docker push $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
