name: Build & Publish Docker Image

on:
  push:
    tags:
    - '[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to Github registry
      run: docker login docker.pkg.github.com -u jujulego -p ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image
      run: docker build -t tpe-web .
    - name: Publish Docker image
      run: |
        docker tag tpe-web docker.pkg.github.com/jujulego/tpe/tpe-web:latest
        docker tag tpe-web docker.pkg.github.com/jujulego/tpe/tpe-web:$(echo ${GITHUB_REF:10})
        docker push docker.pkg.github.com/jujulego/tpe/tpe-web:$(echo ${GITHUB_REF:10})
